/*
    src/browser/bounds_changed_state_tracker.js
 */

const windowTransaction = require('electron').windowTransaction;

import * as _ from 'underscore';
import * as animations from './animations.js';
import * as coreState from './core_state.js';
import * as os from 'os';
import * as Deferred from './deferred';
import WindowGroups from './window_groups';
import WindowGroupTransactionTracker, { ITransaction } from './window_group_transaction_tracker';
import { toSafeInt } from '../common/safe_int';
import ofEvents from './of_events';
import route from '../common/route';
import { clipBounds, windowSetBoundsToVisible } from './utils';
import { OpenFinWindow, BrowserWindow } from '../shapes';
import { Rectangle } from 'electron';
import Bounds from '../../node_modules/hadouken-js-adapter/out/types/src/api/window/bounds';
import { WindowOptions } from '../shapes';

const isWin32 = process.platform === 'win32';
const isWin10 = isWin32 && os.release().startsWith('10');

const DisableWindowGroupTracking = 'disable-window-group-tracking';
// Added Runtime argument: --disable-group-window-tracking=resize,api
// resize: core does not handle resize event for grouped windows
// api: core does not handle bound-changed event for grouped windows if generated by OpenFin API calls
// so with disable-group-window-tracking="resize,api", docking framework can customize resize behaviors
// for grouped windows

const shouldTrack = (action: string) => {
    // track everything by default
    return !coreState.argo[DisableWindowGroupTracking] ||
        !coreState.argo[DisableWindowGroupTracking].split(',').includes(action);
};
const trackingResize = shouldTrack('resize');
const trackingAPI = shouldTrack('api');

interface DecoratedBounds extends Rectangle {
    frame: boolean;
    windowState: WindowState;
}
interface BoundChanged {
    x: boolean;
    x2: boolean;
    y: boolean;
    y2: boolean;
    width: boolean;
    height: boolean;
}

enum WindowState {
    Normal = 'normal',
    Maximized = 'maximized',
    Minimized = 'minimized'
}
interface DefferedEvent {
    changeType: number;
    reason: string;
    name: string;
    uuid: string;
    type: string;
    deferred: boolean;
    top: number;
    left: number;
    height: number;
    width: number;
}

export class BoundsChangedStateTracker {
    private _listeners: any;
    constructor(private uuid: string, private name: string, private browserWindow: BrowserWindow) {
        this._listeners = {
            'begin-user-bounds-change': () => {
                this.setUserBoundsChangeActive(true);
                const cachedBounds = this.getCachedBounds();
                const payload = { uuid, name, top: cachedBounds.y, left: cachedBounds.x };
                ofEvents.emit(route.window('begin-user-bounds-changing', uuid, name), Object.assign(payload, cachedBounds));
            },
            'end-user-bounds-change': () => {
                this.setUserBoundsChangeActive(false);
                const bounds = this.getCurrentBounds();
                const payload = { uuid, name, top: bounds.y, left: bounds.x };
                ofEvents.emit(route.window('end-user-bounds-changing', uuid, name), Object.assign(payload, bounds));
                this.handleBoundsChange(false, true);
            },
            'bounds-changed': () => {
                const ofWindow = coreState.getWindowByUuidName(uuid, name);
                const groupUuid = ofWindow ? ofWindow.groupUuid : null;

                const dispatchedChange = this.handleBoundsChange(true);

                if (dispatchedChange) {
                    if (groupUuid) {
                        const groupLeader = WindowGroupTransactionTracker.getGroupLeader(groupUuid);
                        if (groupLeader && groupLeader.type === 'api') {
                            this.handleBoundsChange(false, true);
                        }
                    } else {
                        if (!animations.getAnimationHandler().hasWindow(this.browserWindow.id) && !this.isUserBoundsChangeActive()) {
                            this.handleBoundsChange(false, true);
                        }
                    }
                }
            },
            'synth-animate-end': (meta: any) => {
                if (meta.bounds) {
                    // COMMENT THIS OUT FOR TESTING FLICKERING
                    this.handleBoundsChange(false, true);
                }
            },
            'visibility-changed': (event: any, isVisible: boolean) => {
                if (!isVisible || this.browserWindow.isMinimized() || this.browserWindow.isMaximized()) {
                    this._deferred = true;
                } else {
                    this._deferred = false;
                    this.dispatchDeferredEvents();
                }
            },
            'minimize': () => {
                this._deferred = true;
                this.updateCachedBounds(this.getCurrentBounds());
            },
            'maximize': () => {
                this._deferred = true;
                this.updateCachedBounds(this.getCurrentBounds());
            },
            'restore': () => {
                this._deferred = false;
                windowSetBoundsToVisible(this.browserWindow);
                this.updateCachedBounds(this.getCurrentBounds());
                this.dispatchDeferredEvents();
            },
            'unmaximize': () => {
                this._deferred = false;
                this.updateCachedBounds(this.getCurrentBounds());
                this.dispatchDeferredEvents();
            },
            'deferred-set-bounds': (event: any, payload: any) => {
                Deferred.handleMove(this.browserWindow.id, payload);
            }
        };
        // Cache the current bounds on construction
        this.updateCachedBounds(this.getCurrentBounds());

        // listen to relevant browser-window events
        this.hookListeners();
    }
    // a flag that represents if any change in the size has happened
    // without relying on the checking of the previous bounds which
    // may or may not be reliable depending on the previous event (
    // specifically bounds-changing)
    private sizeChanged = false;
    private positionChanged = false;

    private _cachedBounds: DecoratedBounds;
    private _userBoundsChangeActive = false;

    private _deferred = false;
    private _deferredEvents: DefferedEvent[] = [];

    private setUserBoundsChangeActive = (enabled: boolean) => {
        this._userBoundsChangeActive = enabled;
    };

    private isUserBoundsChangeActive = () => {
        return this._userBoundsChangeActive;
    };

    private updateCachedBounds = (bounds: DecoratedBounds) => {
        this._cachedBounds = bounds;
    };

    public getCachedBounds = () => {
        return this._cachedBounds;
    };

    private getCurrentBounds = (): DecoratedBounds => {
        const bounds = this.browserWindow.getBounds();

        let windowState = WindowState.Normal;
        if (this.browserWindow.isMaximized()) {
            windowState = WindowState.Maximized;
        }
        if (this.browserWindow.isMinimized()) {
            windowState = WindowState.Minimized;
        }
        const frame = this.browserWindow._options.frame;
        return { ...bounds, frame, windowState };
    };

    private compareBoundsResult = (boundsOne: DecoratedBounds, boundsTwo: DecoratedBounds) => {
        let xDiff = boundsOne.x !== boundsTwo.x;
        let yDiff = boundsOne.y !== boundsTwo.y;
        const widthDiff = boundsOne.width !== boundsTwo.width;
        const heightDiff = boundsOne.height !== boundsTwo.height;
        const stateDiff = boundsOne.windowState !== boundsTwo.windowState;
        const changed = xDiff || yDiff || widthDiff || heightDiff /* || stateDiff*/;

        // set the changed flag only if it has not been set
        this.sizeChanged = this.sizeChanged || (widthDiff || heightDiff);
        if (this.sizeChanged) {
            xDiff = xDiff && ((boundsOne.x - boundsTwo.x) !== (boundsTwo.width - boundsOne.width));
            yDiff = yDiff && ((boundsOne.y - boundsTwo.y) !== (boundsTwo.height - boundsOne.height));
        }
        this.positionChanged = this.positionChanged || (xDiff || yDiff);


        return {
            x: xDiff,
            y: yDiff,
            width: widthDiff,
            height: heightDiff,
            state: stateDiff,
            changed
        };
    };

    private getBoundsDelta = (current: Rectangle, cached: Rectangle) => {
        return {
            x: current.x - cached.x,
            x2: (current.x + current.width) - (cached.x + cached.width),
            y: current.y - cached.y,
            y2: (current.y + current.height) - (cached.y + cached.height),
            width: current.width - cached.width,
            height: current.height - cached.height
        };
    };

    private boundsChangeReason = (name: string, groupUuid?: string) => {
        if (groupUuid) {
            const groupLeader = WindowGroupTransactionTracker.getGroupLeader(groupUuid);

            if (groupLeader && groupLeader.uuid && groupLeader.name) {
                const ofWindow = coreState.getWindowByUuidName(groupLeader.uuid, groupLeader.name);
                if (ofWindow && animations.getAnimationHandler().hasWindow(ofWindow.browserWindow.id)) {
                    return groupLeader.name === name ? 'animation' : 'group-animation';
                } else {
                    return groupLeader.name === name ? 'self' : 'group';
                }
            }
        }

        return animations.getAnimationHandler().hasWindow(this.browserWindow.id) ? 'animation' : 'self';
    };

    private sharedBoundPixelDiff = 15;
    private sharedBound = (boundOne: number, boundTwo: number) => {
        return Math.abs(boundOne - boundTwo) < this.sharedBoundPixelDiff;
    };

    private handleGroupedResize = (resizeChangeType: any, delta: Rectangle, originalWindowCachedBounds: DecoratedBounds, windowToUpdate: OpenFinWindow) => {
        if (!trackingResize) {
            return windowToUpdate.browserWindow.getBounds();
        }
        let { x, y, width, height } = windowToUpdate.browserWindow.getBounds();
        if (resizeChangeType.height) {
            if (delta.y) {
                if (this.sharedBound(y, originalWindowCachedBounds.y)) {
                    // resize windows with matching top bound
                    y = toSafeInt(y + delta.y, y);
                    height = height + delta.height;
                }
                if (this.sharedBound(y + height, originalWindowCachedBounds.y)) {
                    // resize windows with matching bottom bound
                    height = height - delta.height;
                }
            }
            if (delta.y2) {
                if (this.sharedBound(y + height, originalWindowCachedBounds.y + originalWindowCachedBounds.height)) {
                    // resize windows with matching bottom bound
                    height = height + delta.height;
                }
                if (this.sharedBound(y, originalWindowCachedBounds.y + originalWindowCachedBounds.height)) {
                    // resize windows with matching top bound
                    y = toSafeInt(y + delta.height, y);
                    height = height - delta.height;
                }
            }
        }

        if (resizeChangeType.width) {
            if (delta.x) {
                if (this.sharedBound(x, originalWindowCachedBounds.x)) {
                    // resize windows with matching left bound
                    x = toSafeInt(x + delta.x, x);
                    width = width + delta.width;
                }
                if (this.sharedBound(x + width, originalWindowCachedBounds.x)) {
                    // resize windows with matching right bound
                    width = width - delta.width;
                }
            }
            if (delta.x2) {
                if (this.sharedBound(x + width, originalWindowCachedBounds.x + originalWindowCachedBounds.width)) {
                    // resize windows with matching right bound
                    width = width + delta.width;
                }
                if (this.sharedBound(x, originalWindowCachedBounds.x + originalWindowCachedBounds.width)) {
                    // resize windows with matching left bound
                    x = toSafeInt(x + delta.width, x);
                    width = width - delta.width;
                }
            }
        }
        const newWindowBounds = { x, y, width, height };
        const newClippedBounds = clipBounds(newWindowBounds, windowToUpdate.browserWindow);
        return newClippedBounds;
    };

    private checkTrackingApi = (groupLeader: ITransaction) => groupLeader.type === 'api' ? trackingAPI : true;

    private handleBoundsChange = (isAdditionalChangeExpected: boolean, force = false) => {

        let dispatchedChange = false;

        const currentBounds = this.getCurrentBounds();
        const cachedBounds = this.getCachedBounds();
        const boundsCompare = this.compareBoundsResult(currentBounds, cachedBounds);
        const stateMin = boundsCompare.state && currentBounds.state === 'minimized';

        const eventType = isAdditionalChangeExpected ? 'bounds-changing' :
            'bounds-changed';

        const sizeChangedCriteria = [
            boundsCompare.width,
            boundsCompare.height
        ];

        const positionChangedCriteria = [
            boundsCompare.x,
            boundsCompare.y
        ];

        const isBoundsChanged = eventType === 'bounds-changed';

        // if this is to be the "last" event in a transaction, be sure to
        // any diff in the size or position towards the change type
        if (isBoundsChanged) {
            sizeChangedCriteria.push(this.sizeChanged);
            positionChangedCriteria.push(this.positionChanged);
        }

        if (boundsCompare.changed && !stateMin || force) {

            // returns true if any of the criteria are true
            const sizeChange = _.some(sizeChangedCriteria, (criteria) => {
                return criteria;
            });

            const posChange = _.some(positionChangedCriteria, (criteria) => {
                return criteria;
            });

            //const posChange = boundsCompare.x || boundsCompare.y;

            //0 means a change in position.
            //1 means a change in size.
            //2 means a change in position and size.
            // Default to change in position when there is no change
            const changeType = (sizeChange ? (posChange ? 2 : 1) : 0);

            const ofWindow = coreState.getWindowByUuidName(this.uuid, this.name);
            const groupUuid = ofWindow ? ofWindow.groupUuid : null;

            // determine what caused the bounds change
            const reason = this.boundsChangeReason(this.name, groupUuid);

            // handle window group movements
            if (groupUuid) {
                let groupLeader = WindowGroupTransactionTracker.getGroupLeader(groupUuid);

                if (force) {
                    if (groupLeader && groupLeader.name === this.name) {
                        // no need to notify group members for api moves since every window
                        // will already receive an end notification
                        if (groupLeader.type !== 'api') {
                            WindowGroupTransactionTracker.notifyEndTransaction(groupUuid);
                        }
                        WindowGroupTransactionTracker.clearGroup(groupUuid);
                    }
                } else {
                    if (!groupLeader || !groupLeader.name) {
                        const type = this.isUserBoundsChangeActive()
                            ? 'user'
                            : animations.getAnimationHandler().hasWindow(this.browserWindow.id)
                                ? 'animation'
                                : 'api';
                        WindowGroupTransactionTracker.setGroupLeader(groupUuid, this.name, this.uuid, type);
                    }
                }

                groupLeader = WindowGroupTransactionTracker.getGroupLeader(groupUuid);
                if (groupLeader && groupLeader.name === this.name && this.checkTrackingApi(groupLeader)) {
                    const delta = this.getBoundsDelta(currentBounds, cachedBounds);
                    let wt: { on: (arg0: string, arg1: (event: any, payload: any) => void) => void; setWindowPos: (arg0: number, arg1: { x: any; y: any; w: any; h: any; flags: any; }) => void; commit: () => void; }; // window-transaction
                    const hwndToId: { [hwnd: number]: string } = {};

                    const { flag: { noZorder, noSize, noActivate } } = windowTransaction;
                    let flags;
                    if (changeType === 1) {
                        // this may need to change to 1 or 2 if we fix functionality for changeType 2
                        flags = noZorder + noActivate;
                    } else {
                        flags = noZorder + noSize + noActivate;
                    }

                    WindowGroups.getGroup(groupUuid).filter((win) => {
                        win.browserWindow.bringToFront();
                        return win.name !== this.name;
                    }).forEach((win) => {
                        const winBounds = win.browserWindow.getBounds();
                        const bounds = (changeType === 1)
                            ? this.handleGroupedResize(boundsCompare, delta, cachedBounds, win)
                            : winBounds;
                        let {x, y} = bounds;
                        const {width, height} = bounds;
                        // If it is a change in position (working correctly) or a change in position and size (not yet implemented)
                        if (changeType === 0 || changeType === 2) {
                            x = toSafeInt(x + delta.x, x);
                            y = toSafeInt(y + delta.y, y);
                        }

                        if (isWin32) {
                            const hwnd = parseInt(win.browserWindow.nativeId, 16);

                            if (!wt) {
                                wt = new windowTransaction.Transaction(0);

                                wt.on('deferred-set-window-pos', (event, payload) => {
                                    payload.forEach((winPos) => {
                                        const bwId = hwndToId[parseInt(winPos.hwnd)];
                                        Deferred.handleMove(bwId, winPos);
                                    });
                                });
                            }
                            hwndToId[hwnd] = win.browserWindow.id;
                            if (win.browserWindow.isMaximized()) {
                                win.browserWindow.unmaximize();
                            }
                            const [w, h] = [width, height];
                            wt.setWindowPos(hwnd, { x, y, w, h, flags });
                        } else {
                            if (win.browserWindow.isMaximized()) {
                                win.browserWindow.unmaximize();
                            }
                            // no need to call clipBounds here because called earlier
                            win.browserWindow.setBounds({ x, y, width, height });
                        }
                    });

                    if (wt) {
                        wt.commit();
                    }
                }
            }

            const payload = {
                changeType,
                reason,
                name: this.name,
                uuid: this.uuid,
                type: eventType,
                deferred: this._deferred,
                top: currentBounds.y,
                left: currentBounds.x,
                height: currentBounds.height,
                width: currentBounds.width
            };

            if (this._deferred) {
                this._deferredEvents.push(payload);
            } else {
                this.browserWindow.emit('synth-bounds-change', payload);
            }

            dispatchedChange = true;
        }

        this.updateCachedBounds(currentBounds);

        // this represents the changed event, reset the overall changed flag
        if (!isAdditionalChangeExpected) {
            this.sizeChanged = false;
            this.positionChanged = false;
        }

        return dispatchedChange;
    };

    private collapseEventReasonTypes = (eventsList: DefferedEvent[]) => {
        const eventGroups: DefferedEvent[][] = [];

        eventsList.forEach((event, index) => {
            if (index === 0 || event.reason !== eventsList[index - 1].reason) {
                const list = [];
                list.push(event);
                eventGroups.push(list);
            } else {
                _.last(eventGroups).push(event);
            }
        });

        return eventGroups.map((group) => {
            let sizeChange = false;
            let posChange = false;

            group.forEach((event) => {
                if (event.changeType === 0) {
                    posChange = true;
                } else if (event.changeType === 1) {
                    sizeChange = true;
                } else {
                    sizeChange = true;
                    posChange = true;
                }
            });

            const lastEvent = _.last(group);
            lastEvent.changeType = (sizeChange ? (posChange ? 2 : 1) : 0);

            return lastEvent;
        });
    };

    private dispatchDeferredEvents = () => {
        const boundsChangedEvents = this._deferredEvents.filter((event) => {
            return event.type === 'bounds-changed';
        });

        const reasonGroupedEvents = this.collapseEventReasonTypes(boundsChangedEvents);

        reasonGroupedEvents.forEach((event) => {
            event.type = 'bounds-changing';
            this.browserWindow.emit('synth-bounds-change', event);
            event.type = 'bounds-changed';
            this.browserWindow.emit('synth-bounds-change', event);
        });

        this._deferredEvents.length = 0;
    };


    private endWindowGroupTransactionListener = (groupUuid: string) => {
        const ofWindow = coreState.getWindowByUuidName(this.uuid, this.name);
        const _groupUuid = ofWindow ? ofWindow.groupUuid : null;

        if (_groupUuid === groupUuid) {
            const groupLeader = WindowGroupTransactionTracker.getGroupLeader(groupUuid);

            if (groupLeader && groupLeader.name !== this.name) {
                this.handleBoundsChange(false, true);
            }
        }
    };

    private updateEvents = (register: boolean) => {
        const listenerFn = register ? 'on' : 'removeListener';

        Object.keys(this._listeners).forEach((key) => {
            this.browserWindow[listenerFn](key, this._listeners[key]);
        });

        WindowGroupTransactionTracker[listenerFn]('end-window-group-transaction', this.endWindowGroupTransactionListener);
    };

    private hookListeners = () => {
        this.updateEvents(true);
    };

    private unHookListeners = () => {
        this.updateEvents(false);
    };

    // Remove all event listeners this instance subscribed on
    private teardown = () => {
        this.unHookListeners();
    };

}

